# Backend utilities for data processing and LLM interactions
# Handles code generation, validation, and helper functions
import os
import re

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from langchain_groq import ChatGroq

from agents.llm_fallback import is_rate_limit_error, build_limit_exceeded_message


# Extract Python code from LLM response (removes markdown formatting)
def extract_python_code(text: str) -> str:
    code_match = re.search(r"```python\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if code_match:
        return code_match.group(1).strip()
    return text.strip()


# Ensure generated code is safe by blocking dangerous operations
def validate_generated_code(code: str) -> tuple[bool, str]:
    # List of operations we don't allow for security reasons
    blocked_patterns = [
        "import ",
        "from ",
        "open(",
        "exec(",
        "eval(",
        "__",
        "os.",
        "sys.",
        "subprocess",
        "shutil",
        "pathlib",
        "requests",
    ]
    # Check if any blocked patterns are in the code
    lower_code = code.lower()
    for pattern in blocked_patterns:
        if pattern in lower_code:
            return False, f"Blocked operation detected: {pattern.strip()}"
    return True, ""


# Safely execute pandas code generated by AI
def run_generated_pandas_code(df: pd.DataFrame, code: str):
    # Validate code first
    is_valid, err = validate_generated_code(code)
    if not is_valid:
        return None, None, err

    # Set up safe environment for code execution
    local_vars = {
        "df": df.copy(),
        "pd": pd,
        "np": np,
        "result": None,
        "chart": None,
        "chart_x": None,
        "chart_y": None,
    }

    # Try to run the code safely
    try:
        exec(code, {"__builtins__": {}}, local_vars)
    except Exception as e:
        return None, None, str(e)

    # Get results from the executed code
    result = local_vars.get("result")
    chart_cfg = {
        "chart": local_vars.get("chart"),
        "chart_x": local_vars.get("chart_x"),
        "chart_y": local_vars.get("chart_y"),
    }
    return result, chart_cfg, None


# Build rate limit error message
def rate_limit_message(err: Exception) -> str:
    if is_rate_limit_error(err):
        return build_limit_exceeded_message(err)
    return ""


# Find rate limit messages in text
def extract_limit_message(text: str) -> str:
    if not text:
        return ""
    patterns = [
        r"Groq limit exceeded\. Use after [^.\n]+\.",
        r"Groq limit exceeded\. Please try again later\.",
    ]
    for pattern in patterns:
        match = re.search(pattern, text)
        if match:
            return match.group(0)
    return ""


# Remove rate limit messages from text
def remove_limit_message(text: str) -> str:
    limit_msg = extract_limit_message(text)
    if not limit_msg:
        return text
    cleaned = text.replace(f"\n\nAI Summary:\n{limit_msg}", "")
    cleaned = cleaned.replace(limit_msg, "")
    return cleaned.strip()


# Invoke LLM directly for quick questions (uses Groq API)
def invoke_llm_with_fallback(prompt: str) -> str:
    # Import messaging components from LangChain
    from langchain_core.messages import SystemMessage, HumanMessage

    load_dotenv()

    # Get LLM model and API key from environment
    groq_model = os.getenv("MODEL_NAME", "llama-3.3-70b-versatile")
    groq_key = os.getenv("GROQ_API_KEY", "").strip()

    if not groq_key:
        raise RuntimeError("GROQ_API_KEY is missing.")

    # System message that gives instructions to the AI
    system_message = """You are a data analyst assistant. When answering questions about data:
1. Include relevant formulas/equations (use markdown notation like `formula` or math expressions)
2. Keep your response concise and to-the-point (max 3-4 sentences unless asked for details)
3. Lead with the answer, then briefly explain the approach
4. Use bullet points for multiple items
5. Show calculations only when necessary for clarity"""

    # Create Groq LLM instance
    groq_llm = ChatGroq(model=groq_model, api_key=groq_key)

    # Prepare messages for the LLM
    messages = [
        SystemMessage(content=system_message),
        HumanMessage(content=prompt),
    ]

    # Send to LLM and get response
    return groq_llm.invoke(messages).content


# Suggest example questions based on the data columns
def dataset_examples(df: pd.DataFrame) -> tuple[str, str]:
    # Get column names
    cols = list(df.columns)
    if not cols:
        return (
            "What are the main trends in this dataset?",
            "Show top 10 rows sorted by a key metric",
        )

    # Find numeric and categorical columns
    numeric_cols = list(df.select_dtypes(include=np.number).columns)
    categorical_cols = list(df.select_dtypes(include=["object", "category", "bool"]).columns)

    # Helper to find relevant column by name
    def pick_column(candidates, contains_terms):
        for col in candidates:
            col_name = str(col).lower()
            if any(term in col_name for term in contains_terms):
                return col
        return candidates[0] if candidates else None

    # Find relevant columns by name patterns
    customer_col = pick_column(categorical_cols + cols, ["customer", "client", "user", "name", "account"])
    metric_col = pick_column(numeric_cols + cols, ["revenue", "sales", "amount", "price", "profit", "total"])
    time_col = pick_column(cols, ["date", "month", "year", "time", "period"])

    # Create example Q&A question
    qna_example = f"What are the top 5 {customer_col} by {metric_col}?" if customer_col and metric_col else (
        f"What insights can you share about {metric_col}?" if metric_col else f"What does {cols[0]} tell us about performance?"
    )

    # Create example pandas code question
    if customer_col and metric_col:
        pandas_example = f"Show top 10 {customer_col} by {metric_col}"
    elif time_col and metric_col:
        pandas_example = f"Show {metric_col} trend by {time_col}"
    elif metric_col:
        pandas_example = f"Show summary statistics for {metric_col}"
    else:
        pandas_example = f"Show top 10 values in {cols[0]}"

    return qna_example, pandas_example


    # Convert datetime columns
def prepare_dashboard_df(df: pd.DataFrame) -> pd.DataFrame:
    # Make a copy to avoid changing original
    dashboard_df = df.copy()
    # Try to convert object columns that look like dates
    for col in dashboard_df.columns:
        # Try parsing as datetime
        if dashboard_df[col].dtype == "object":
            parsed = pd.to_datetime(dashboard_df[col], errors="coerce")
            if parsed.notna().mean() >= 0.7:
                dashboard_df[col] = parsed
    return dashboard_df
